/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes/_authenticated/admin/account'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin/quotes'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
